const test=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const fs=require('node:fs/promises');const {pathToFileURL}=require('node:url');const {assertNoPrivate}=require('./support/disclosure.cjs');
// Do not enable in the current restricted environment. Opt-in is for a separate permitted host only.
const enabled=process.env.OMINOUS_BROWSER_QA==='1';
const reason='Not run: browser launch/IPC restrictions. No browser launch or permission bypass attempted.';
let browser,context,page;const networkRequests=[];const errors=[];const root=path.resolve(__dirname,'..');
async function scan(){const text=await page.evaluate(()=>document.documentElement.outerHTML);assertNoPrivate(text);}
test.before(async()=>{if(!enabled)return;const {chromium}=require('playwright');browser=await chromium.launch({headless:true,chromiumSandbox:true,...(process.env.OMINOUS_CHROMIUM_EXECUTABLE?{executablePath:process.env.OMINOUS_CHROMIUM_EXECUTABLE}:{})});context=await browser.newContext({viewport:{width:1920,height:1080}});await context.route(/^https?:/,route=>{networkRequests.push(route.request().url());return route.abort();});page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await fs.mkdir(path.join(root,'out/owner-review/browser'),{recursive:true});});
test.beforeEach(async()=>{if(enabled){await page.emulateMedia({reducedMotion:'no-preference'});await page.goto(pathToFileURL(path.join(root,'out/public/index.html')).href);}});
test.after(async()=>{if(browser)await browser.close();});
const check=(name,fn)=>test(name,{skip:enabled?false:reason},fn);
check('approved public copy and honest demo status appear',async()=>{assert.equal(await page.locator('#display-title').textContent(),'Ominous');assert.equal(await page.locator('#display-summary').textContent(),'Presentation demo ready.');assert.equal(await page.locator('#display-status').textContent(),'Demo: ready');assert((await page.locator('footer').textContent()).includes('No live core connected'));});
check('DOM and accessibility attributes contain no private marker',async()=>{await scan();assertNoPrivate(JSON.stringify(await page.locator('[aria-label],[aria-live],[title],[alt]').evaluateAll(nodes=>nodes.map(n=>Array.from(n.attributes,attribute=>[attribute.name,attribute.value])))));});
check('browser disclosure checker catches injected synthetic marker',async()=>{await page.evaluate(()=>document.body.dataset.syntheticProbe='OMINOUS_PRIVATE_BROWSER_PROBE_24');await assert.rejects(scan,/Private fixture marker/);await page.evaluate(()=>delete document.body.dataset.syntheticProbe);await scan();});
check('state changes and repeated selections clear stale success',async()=>{for(const state of ['loading','ready','blocked','error','error','cancelled','ready']){await page.selectOption('#preview-state',state);assert.equal(await page.locator('#display-status').textContent(),'Demo: '+state);assert.equal(await page.locator('#display-summary').textContent(),'');assert.equal(await page.locator('#display-caption').textContent(),'');await scan();}});
check('manual reduced motion stops decorative animation',async()=>{await page.click('#motion-toggle');assert.equal(await page.locator('#motion-toggle').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('.ghost').evaluate(n=>getComputedStyle(n).animationName),'none');const a=await page.locator('.ghost').evaluate(n=>getComputedStyle(n).transform);await page.waitForTimeout(200);assert.equal(await page.locator('.ghost').evaluate(n=>getComputedStyle(n).transform),a);});
check('device reduced motion stays respected after repeated toggles',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await page.click('#motion-toggle');await page.click('#motion-toggle');assert.equal(await page.locator('.ghost').evaluate(n=>getComputedStyle(n).animationName),'none');});
check('desktop and mobile layouts have no horizontal overflow',async()=>{for(const [width,height] of [[1920,1080],[960,540],[390,844]]){await page.setViewportSize({width,height});await scan();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await page.screenshot({path:path.join(root,`out/owner-review/browser/${width}x${height}.png`),fullPage:true});}});
check('15-second frame-cadence target is measured on this host',async()=>{await page.bringToFront();const intervals=await page.evaluate(()=>new Promise(resolve=>{let start,last;const values=[];function frame(now){if(start===undefined)start=now;if(last!==undefined)values.push(now-last);last=now;if(now-start<15000)requestAnimationFrame(frame);else resolve(values);}requestAnimationFrame(frame);}));const sorted=intervals.slice().sort((a,b)=>a-b);const metrics={browser:browser.version(),samples:sorted.length,p95Ms:sorted[Math.ceil(sorted.length*.95)-1],maxGapMs:Math.max(...sorted),scope:'one 15-second foreground run; not universal smoothness'};await fs.writeFile(path.join(root,'out/owner-review/browser/motion-metrics.json'),JSON.stringify(metrics,null,2));assert(metrics.samples>0);assert(metrics.p95Ms<=34);assert(metrics.maxGapMs<=100);});
check('presentation makes no network requests',async()=>assert.deepEqual(networkRequests,[]));
check('presentation emits no page errors',async()=>assert.deepEqual(errors,[]));
