import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';
import {BROWSER_SCRIPT} from '../src/browser-script.mjs';import {projectPublic} from '../src/public-view.mjs';import {transitionPublic} from '../src/state.mjs';import disclosure from './support/disclosure.cjs';
// This checks fixed controller logic against a tiny fake DOM; it is not browser QA.
function harness(prefers=false){
 const record={title:'Ominous',summary:'Demo ready',caption:'Safe caption',status:'ready',private:'OMINOUS_PRIVATE_CONTROLLER_24'};const view=projectPublic(record,['title','summary','caption']);const elements={};
 for(const id of ['public-data','preview-state','motion-toggle','display-title','display-summary','display-caption','display-status'])elements[id]={textContent:'',value:'',attrs:{},handlers:{},setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,v){this.handlers[k]=v;}};
 elements['public-data'].textContent=JSON.stringify(view);const body={dataset:{reducedMotion:'false'}};const preference={matches:prefers,addEventListener(){}};
 vm.runInNewContext(BROWSER_SCRIPT,{document:{getElementById:id=>elements[id],body},window:{matchMedia:()=>preference}},{timeout:1000});return {view,elements,body};
}
test('controller only paints public text',()=>{const h=harness();assert.equal(h.elements['display-summary'].textContent,'Demo ready');disclosure.assertNoPrivate(JSON.stringify(h.elements));});
test('controller states agree with shared transition rules and clear stale results',()=>{const h=harness();let expected=h.view;for(const status of ['loading','ready','error','error','blocked','cancelled','idle','ready','OMINOUS_PRIVATE_BAD_STATE_24']){h.elements['preview-state'].handlers.change({target:{value:status}});expected=transitionPublic(expected,['idle','loading','ready','blocked','error','cancelled'].includes(status)?status:'error');assert.equal(h.elements['display-status'].textContent,'Demo: '+expected.status);assert.equal(h.elements['display-summary'].textContent,expected.summary);assert.equal(h.elements['display-caption'].textContent,expected.caption);disclosure.assertNoPrivate(JSON.stringify(h.elements));}});
test('repeated motion toggles preserve status and set accessibility state',()=>{const h=harness();for(let i=0;i<4;i++){h.elements['motion-toggle'].handlers.click();assert.equal(h.body.dataset.reducedMotion,String(i%2===0));assert.equal(h.elements['motion-toggle'].attrs['aria-pressed'],String(i%2===0));assert.equal(h.elements['display-status'].textContent,'Demo: ready');}});
test('device reduced-motion preference remains respected',()=>{const h=harness(true);h.elements['motion-toggle'].handlers.click();h.elements['motion-toggle'].handlers.click();assert.equal(h.body.dataset.reducedMotion,'true');assert.equal(h.elements['motion-toggle'].textContent,'Reduced by device');});
