import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,readdir,writeFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import path from 'node:path';import {spawnSync} from 'node:child_process';
import {projectPublic} from '../src/public-view.mjs';
let api={};try{api=await import('../src/export.mjs');}catch(e){if(e.code!=='ERR_MODULE_NOT_FOUND')throw e;}
const fixture=JSON.parse(await readFile(new URL('../fixtures/approved.json',import.meta.url),'utf8'));
const view=()=>projectPublic(fixture.record,fixture.approval);
const call=(...args)=>{assert.equal(typeof api.exportPublic,'function','exportPublic is implemented');return api.exportPublic(...args);};
const run=(args)=>spawnSync(process.execPath,['bin/demo.mjs',...args],{cwd:new URL('..',import.meta.url),encoding:'utf8'});
test('exports one approved view as HTML JSON and SRT',()=>{
 const out=call(view());assert.deepEqual(Object.keys(out).sort(),['html','json','srt']);assert(out.html.includes('Presentation demo ready.'));assert.deepEqual(JSON.parse(out.json),view());
 assert.equal(out.srt,'1\n00:00:00,000 --> 00:00:15,000\nOnly approved display content appears here.\n');
 assert(!JSON.stringify(out).includes('OMINOUS_PRIVATE_'));
});
test('escapes markup in HTML and caption exports',()=>{const r={...fixture.record,title:'<img src=x onerror=alert(1)>',caption:'</script><script>alert(1)</script>'};const out=call(projectPublic(r,fixture.approval));assert(out.html.includes('&lt;img'));assert(!out.html.includes('<img src=x'));assert(!out.html.includes('</script><script>alert'));assert.equal(JSON.parse(out.json).caption,r.caption);assert(out.srt.includes('&lt;/script&gt;'));});
test('strict extra view keys produce safe error exports',()=>{const out=call({...view(),private:'OMINOUS_PRIVATE_EXTRA_24'});assert.equal(JSON.parse(out.json).status,'error');assert.equal(JSON.parse(out.json).title,'');assert(!JSON.stringify(out).includes('OMINOUS_PRIVATE_'));assert.equal(out.srt,'');});
for(const status of ['idle','loading','blocked','error','cancelled'])test(`${status} export has no stale caption or summary`,()=>{const v=projectPublic({...fixture.record,status},fixture.approval);const out=call(v);assert.equal(out.srt,'');assert(!out.html.includes('Presentation demo ready.'));assert.equal(JSON.parse(out.json).status,status);});
test('denied view uses safe empty content',()=>{const out=call(projectPublic(fixture.record,[]));assert.equal(JSON.parse(out.json).title,'');assert.equal(out.srt,'');assert(!out.html.includes(fixture.record.caption));});
test('public HTML contains no network or owner diagnostic route',()=>{const html=call(view()).html;for(const forbidden of ['owner-review','fixtures/','file:///','sourceMappingURL','fetch(','XMLHttpRequest','<iframe'])assert(!html.includes(forbidden));assert(html.includes("connect-src 'none'"));assert(html.includes('Synthetic preview'));});
test('reduced motion option is explicit',()=>{assert(call(view(),{reducedMotion:true}).html.includes('data-reduced-motion="true"'));assert(call(view(),{reducedMotion:false}).html.includes('data-reduced-motion="false"'));});
test('CLI writes only three public files and one separate receipt',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'ominous-test-'));const out=path.join(dir,'output');const result=run(['--fixture','fixtures/approved.json','--out',out]);assert.equal(result.status,0,result.stderr);assert.deepEqual((await readdir(path.join(out,'public'))).sort(),['captions.srt','index.html','view.json']);assert.deepEqual(await readdir(path.join(out,'owner-review')),['receipt.json']);const receipt=await readFile(path.join(out,'owner-review/receipt.json'),'utf8');assert(!receipt.includes('OMINOUS_PRIVATE_'));assert.equal(JSON.parse(receipt).publicStatus,'ready');});
test('CLI refuses overwrite and preserves prior files',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'ominous-test-'));const out=path.join(dir,'output');const args=['--fixture','fixtures/approved.json','--out',out];assert.equal(run(args).status,0);const before=await readFile(path.join(out,'public/index.html'));const retry=run(args);assert.equal(retry.status,2);assert.deepEqual(await readFile(path.join(out,'public/index.html')),before);});
test('CLI parse and usage errors do not echo private details',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'ominous-test-'));const file=path.join(dir,'OMINOUS_PRIVATE_FILE_24.json');await writeFile(file,'{ OMINOUS_PRIVATE_PARSE_24');for(const args of [['--fixture',file,'--out',path.join(dir,'out')],['--bad-OMINOUS_PRIVATE_ARG_24'],['--fixture',file]]){const result=run(args);assert.equal(result.status,2);assert(!`${result.stdout}${result.stderr}`.includes('OMINOUS_PRIVATE_'));assert(!`${result.stdout}${result.stderr}`.includes(dir));}});
test('CLI malformed status generates truthful safe error preview',async()=>{const dir=await mkdtemp(path.join(tmpdir(),'ominous-test-'));const out=path.join(dir,'output');const result=run(['--fixture','fixtures/malformed.json','--out',out]);assert.equal(result.status,0,result.stderr);const text=await readFile(path.join(out,'public/view.json'),'utf8');assert.equal(JSON.parse(text).status,'error');assert(!text.includes('OMINOUS_PRIVATE_'));});
